resources:
- backend/deploy.yml
- backend/service.yml
- ingress.yml

images:
- name: 968225077300.dkr.ecr.us-west-1.amazonaws.com/devops-na-nuvem/production/backend
  newName: 968225077300.dkr.ecr.us-west-1.amazonaws.com/devops-na-nuvem/production/backend
  newTag: d955215a955e168637bfb7f27c598726df7ab70b
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
