resources:
  - frontend/deployment.yml
  - frontend/service.yml
  - backend/deployment.yml
  - backend/service.yml
  - ingress.yml

images:
  - name: 968225077300.dkr.ecr.us-west-1.amazonaws.com/minicursodevopsaws/production/backend
    newName: 968225077300.dkr.ecr.us-west-1.amazonaws.com/minicursodevopsaws/production/backend
    newTag: v1.0

  - name: 968225077300.dkr.ecr.us-west-1.amazonaws.com/minicursodevopsaws/production/frontend
    newName: 968225077300.dkr.ecr.us-west-1.amazonaws.com/minicursodevopsaws/production/frontend
    newTag: v1.0
